### ISSUE TITLE
Clean data within Publishers and Snippets

### ISSUE THREAD

**Issue by pranavAbe** [pranavAbe/ReScholar#6]
There is mangled UTF-8 data in the scraped JSON in both the Publishers and Snippets column. Inspecting the JSON will show you what this looks like. Find a way to clean up the data. 

This link might be helpful: https://stackoverflow.com/questions/56955320/file-contain-u00c2-u00a0-convert-to-characters

**Comment by JDRanpariya** [comment]
Check It
