### ISSUE TITLE
Split Publishers Property in JSON

### ISSUE THREAD

**Issue by pranavAbe** [pranavAbe/ReScholar#7]
The current 'publishers' property being scraped contains the Authors, Year, and the Publishing Entity, all in one string (as shown in the screenshot below). Find a way to separate them and have them as three different columns: 'authors', 'year', and 'publishers'. 

![image](https://user-images.githubusercontent.com/29583966/113861245-aa781700-97af-11eb-827e-c3ee7c72200e.png)

Note: Keep in mind that sometimes the order of the above will change depending on the search term. Sometimes it can also be such that it's ordered as, Authors, Journal, Year, and Publishing Entity (as shown in the screenshot below)

![image](https://user-images.githubusercontent.com/29583966/113861168-90d6cf80-97af-11eb-8405-2c14569407c5.png)

**Comment by JDRanpariya** [comment]
need to add fix for second format

**Comment by JDRanpariya** [comment]
done
